//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Aditivo_Entities : DbContext
    {
        public Aditivo_Entities()
            : base("name=Aditivo_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<AlIny10> AlIny10 { get; set; }
        public virtual DbSet<AlIny11> AlIny11 { get; set; }
        public virtual DbSet<AlIny12> AlIny12 { get; set; }
        public virtual DbSet<AlIny13> AlIny13 { get; set; }
        public virtual DbSet<AlIny14> AlIny14 { get; set; }
        public virtual DbSet<AlIny6> AlIny6 { get; set; }
        public virtual DbSet<AlIny7> AlIny7 { get; set; }
        public virtual DbSet<AlIny8> AlIny8 { get; set; }
        public virtual DbSet<AlIny9> AlIny9 { get; set; }
        public virtual DbSet<AlNiv> AlNiv { get; set; }
        public virtual DbSet<AlSkid> AlSkid { get; set; }
        public virtual DbSet<NivTanq> NivTanq { get; set; }
        public virtual DbSet<TotIny10> TotIny10 { get; set; }
        public virtual DbSet<TotIny11> TotIny11 { get; set; }
        public virtual DbSet<TotIny12> TotIny12 { get; set; }
        public virtual DbSet<TotIny13> TotIny13 { get; set; }
        public virtual DbSet<TotIny14> TotIny14 { get; set; }
        public virtual DbSet<TotIny6> TotIny6 { get; set; }
        public virtual DbSet<TotIny7> TotIny7 { get; set; }
        public virtual DbSet<TotIny8> TotIny8 { get; set; }
        public virtual DbSet<TotIny9> TotIny9 { get; set; }
        public virtual DbSet<UCIny10> UCIny10 { get; set; }
        public virtual DbSet<UCIny11> UCIny11 { get; set; }
        public virtual DbSet<UCIny12> UCIny12 { get; set; }
        public virtual DbSet<UCIny13> UCIny13 { get; set; }
        public virtual DbSet<UCIny14> UCIny14 { get; set; }
        public virtual DbSet<UCIny6> UCIny6 { get; set; }
        public virtual DbSet<UCIny7> UCIny7 { get; set; }
        public virtual DbSet<UCIny8> UCIny8 { get; set; }
        public virtual DbSet<UCIny9> UCIny9 { get; set; }
        public virtual DbSet<VolTanq> VolTanq { get; set; }
    }
}
