//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bomba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bomba()
        {
            this.bombas_descargaderas = new HashSet<bombas_descargaderas>();
            this.bombas_llenaderas = new HashSet<bombas_llenaderas>();
            this.tanque_bomba = new HashSet<tanque_bomba>();
        }
    
        public int id_bomba { get; set; }
        public string nombre_bomba { get; set; }
        public string descripcion_bomba { get; set; }
        public string arraque_bomba { get; set; }
        public string paro_bomba { get; set; }
        public string estatus_bomba { get; set; }
        public Nullable<int> hrs_trabajo_acum { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_paro { get; set; }
    
        public virtual paro paro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bombas_descargaderas> bombas_descargaderas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bombas_llenaderas> bombas_llenaderas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tanque_bomba> tanque_bomba { get; set; }
    }
}
