//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bombas_descargaderas
    {
        public int id_bm_des { get; set; }
        public Nullable<int> id_bomba { get; set; }
        public Nullable<int> id_descarga { get; set; }
    
        public virtual bomba bomba { get; set; }
        public virtual descargaderas descargaderas { get; set; }
    }
}
