//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class descargaderas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public descargaderas()
        {
            this.bombas_descargaderas = new HashSet<bombas_descargaderas>();
            this.eventos_alarmas_descargaderas = new HashSet<eventos_alarmas_descargaderas>();
        }
    
        public int id_descarga { get; set; }
        public string nombre_comercializador_producto { get; set; }
        public Nullable<int> no_orden { get; set; }
        public string numero_tranporte { get; set; }
        public Nullable<int> numero_posicion_descarga { get; set; }
        public Nullable<int> clave_producto { get; set; }
        public Nullable<double> vol_programado { get; set; }
        public Nullable<double> vol_natural_medido { get; set; }
        public Nullable<double> vol_neto_entregado_corregido { get; set; }
        public Nullable<double> temperatura_promedio_descarga { get; set; }
        public string densidad_descarga { get; set; }
        public string flujo_promedio_descarga { get; set; }
        public string factor_medicion_promedio_descarga { get; set; }
        public Nullable<System.DateTime> fecha_inicio_descarga { get; set; }
        public Nullable<System.DateTime> fecha_fin_descarga { get; set; }
        public Nullable<System.TimeSpan> hora_inicio_descarga { get; set; }
        public Nullable<System.TimeSpan> hora_fin_descarga { get; set; }
        public string estado_permisivo_tierra { get; set; }
        public Nullable<int> totalizadores_ucls { get; set; }
        public Nullable<int> id_acceso { get; set; }
        public Nullable<int> id_bomba { get; set; }
    
        public virtual accesos accesos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bombas_descargaderas> bombas_descargaderas { get; set; }
        public virtual producto producto { get; set; }
        public virtual operaciones operaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eventos_alarmas_descargaderas> eventos_alarmas_descargaderas { get; set; }
    }
}
