//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventos_alarmas_descargaderas
    {
        public int id_ev_al_des { get; set; }
        public Nullable<int> id_ev_al { get; set; }
        public Nullable<int> id_descarga { get; set; }
        public Nullable<System.DateTime> fecha_ev { get; set; }
        public Nullable<System.TimeSpan> hora_ev { get; set; }
        public Nullable<int> no_orden { get; set; }
    
        public virtual descargaderas descargaderas { get; set; }
        public virtual eventos_alarmas eventos_alarmas { get; set; }
    }
}
