//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventos_alarmas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eventos_alarmas()
        {
            this.eventos_alarmas_llenaderas = new HashSet<eventos_alarmas_llenaderas>();
            this.eventos_alarmas_descargaderas = new HashSet<eventos_alarmas_descargaderas>();
        }
    
        public int id_ev_al { get; set; }
        public string descripcion_ev_al { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eventos_alarmas_llenaderas> eventos_alarmas_llenaderas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eventos_alarmas_descargaderas> eventos_alarmas_descargaderas { get; set; }
    }
}
