//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class llenaderas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public llenaderas()
        {
            this.bombas_llenaderas = new HashSet<bombas_llenaderas>();
            this.eventos_alarmas_llenaderas = new HashSet<eventos_alarmas_llenaderas>();
        }
    
        public int id_llenadera { get; set; }
        public Nullable<int> no_orden { get; set; }
        public Nullable<int> numero_cliente { get; set; }
        public string nombre_comercializador_producto { get; set; }
        public Nullable<int> numero_autotanque { get; set; }
        public Nullable<int> numero_posicion_carga { get; set; }
        public Nullable<int> clave_producto { get; set; }
        public Nullable<double> vol_carga { get; set; }
        public Nullable<double> vol_programado { get; set; }
        public Nullable<double> vol_natural_medido { get; set; }
        public Nullable<double> vol_neto_entregado_compensado { get; set; }
        public Nullable<double> temperatura_promedio_carga { get; set; }
        public Nullable<int> densidad_carga { get; set; }
        public string flujo_promedio_carga { get; set; }
        public string factor_medicion_promedio_carga { get; set; }
        public Nullable<System.DateTime> fecha_inicio_carga { get; set; }
        public Nullable<System.DateTime> fecha_fin_carga { get; set; }
        public Nullable<System.TimeSpan> hora_inicio_carga { get; set; }
        public Nullable<System.TimeSpan> hora_fin_carga { get; set; }
        public string estado_permisivo_tierra { get; set; }
        public string estado_permisivo_sobrellenado { get; set; }
        public Nullable<int> total_aditivos { get; set; }
        public Nullable<int> id_aditivos { get; set; }
        public Nullable<int> id_acceso { get; set; }
    
        public virtual accesos accesos { get; set; }
        public virtual aditivos aditivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bombas_llenaderas> bombas_llenaderas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eventos_alarmas_llenaderas> eventos_alarmas_llenaderas { get; set; }
        public virtual producto producto { get; set; }
        public virtual operaciones operaciones { get; set; }
    }
}
