//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_Entities : DbContext
    {
        public bd_Entities()
            : base("name=bd_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accesos> accesos { get; set; }
        public virtual DbSet<aditivos> aditivos { get; set; }
        public virtual DbSet<Auditoria> Auditoria { get; set; }
        public virtual DbSet<bomba> bomba { get; set; }
        public virtual DbSet<bombas_descargaderas> bombas_descargaderas { get; set; }
        public virtual DbSet<bombas_llenaderas> bombas_llenaderas { get; set; }
        public virtual DbSet<cubicacion> cubicacion { get; set; }
        public virtual DbSet<descargaderas> descargaderas { get; set; }
        public virtual DbSet<Entradas> Entradas { get; set; }
        public virtual DbSet<eventos_alarmas> eventos_alarmas { get; set; }
        public virtual DbSet<eventos_alarmas_descargaderas> eventos_alarmas_descargaderas { get; set; }
        public virtual DbSet<eventos_alarmas_llenaderas> eventos_alarmas_llenaderas { get; set; }
        public virtual DbSet<llenaderas> llenaderas { get; set; }
        public virtual DbSet<operaciones> operaciones { get; set; }
        public virtual DbSet<paro> paro { get; set; }
        public virtual DbSet<poliducto> poliducto { get; set; }
        public virtual DbSet<proceso_voes> proceso_voes { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<Salidas> Salidas { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tanque> tanque { get; set; }
        public virtual DbSet<tanque_bomba> tanque_bomba { get; set; }
        public virtual DbSet<tanque_cubicacion> tanque_cubicacion { get; set; }
        public virtual DbSet<tanque_poliducto> tanque_poliducto { get; set; }
        public virtual DbSet<Tanque_Voe> Tanque_Voe { get; set; }
        public virtual DbSet<voe> voe { get; set; }
    }
}
