//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pendiente_Files
    {
        public int id { get; set; }
        public Nullable<int> id_Pendiente { get; set; }
        public Nullable<int> id_File { get; set; }
    
        public virtual Files Files { get; set; }
        public virtual Pendiente Pendiente { get; set; }
    }
}
