//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proceso_voes
    {
        public int id_proc_voe { get; set; }
        public Nullable<int> estado_val_entrada { get; set; }
        public Nullable<int> estado_val_entrada_poli { get; set; }
        public Nullable<int> estado_val_salida_tq { get; set; }
        public Nullable<int> control_cierre_val_entrada_poli { get; set; }
        public Nullable<int> control_cierre_val_entrada { get; set; }
        public Nullable<int> control_cierre_val_salida_tq { get; set; }
        public Nullable<int> control_apertura_val_entrada_poli { get; set; }
        public Nullable<int> control_apertura_val_entrada { get; set; }
        public Nullable<int> control_apertura_val_salida_tq { get; set; }
        public Nullable<int> control_paro_val_entrada_poli { get; set; }
        public Nullable<int> control_paro_val_entrada { get; set; }
        public Nullable<int> control_paro_val_salida_tq { get; set; }
        public Nullable<int> id_voe { get; set; }
    
        public virtual voe voe { get; set; }
    }
}
