//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recetas
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Producto { get; set; }
        public Nullable<double> Porcentaje_producto { get; set; }
        public Nullable<int> Brazo { get; set; }
        public Nullable<double> Cantidad_aditivo { get; set; }
        public Nullable<double> Razon_flujo { get; set; }
        public Nullable<double> Prod_usando_iny { get; set; }
    }
}
