//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roll_Operacion
    {
        public int id { get; set; }
        public Nullable<int> id_Roll { get; set; }
        public Nullable<int> id_Operacion { get; set; }
    
        public virtual Operacion Operacion { get; set; }
        public virtual Roll Roll { get; set; }
    }
}
