//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tanque_poliducto
    {
        public int id_tq_pd { get; set; }
        public Nullable<int> id_tanque { get; set; }
        public Nullable<int> id_poliducto { get; set; }
        public Nullable<int> no_lote { get; set; }
        public Nullable<double> vol_programado { get; set; }
        public Nullable<System.TimeSpan> hora_inicio { get; set; }
        public Nullable<System.TimeSpan> hora_fin { get; set; }
        public Nullable<double> temperatura_prom_lote { get; set; }
        public Nullable<int> totalizados_lote_actual { get; set; }
        public Nullable<int> masa_total_lote { get; set; }
        public Nullable<int> totalizados_lote_anterior { get; set; }
    
        public virtual poliducto poliducto { get; set; }
        public virtual tanque tanque { get; set; }
    }
}
