//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tanque_bomba
    {
        public int id_tq_bm { get; set; }
        public Nullable<int> id_tanque { get; set; }
        public Nullable<int> id_bomba { get; set; }
    
        public virtual bomba bomba { get; set; }
        public virtual tanque tanque { get; set; }
    }
}
