//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tanque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tanque()
        {
            this.tanque_bomba = new HashSet<tanque_bomba>();
            this.tanque_cubicacion = new HashSet<tanque_cubicacion>();
            this.tanque_poliducto = new HashSet<tanque_poliducto>();
            this.Tanque_Voe = new HashSet<Tanque_Voe>();
        }
    
        public int id_tanque { get; set; }
        public Nullable<double> nivel_prod { get; set; }
        public Nullable<double> tem_prod { get; set; }
        public string estado_control { get; set; }
        public string estado_red { get; set; }
        public string nombre { get; set; }
        public string nom_prod { get; set; }
        public string densidad_prod { get; set; }
        public string capacidad { get; set; }
        public Nullable<double> vol_natural { get; set; }
        public Nullable<double> vol_corregido { get; set; }
        public Nullable<double> vol_bruto { get; set; }
        public Nullable<double> vol_agua { get; set; }
        public Nullable<int> estado_a_nivel { get; set; }
        public Nullable<int> estado_a_a_nivel { get; set; }
        public Nullable<int> estado_b_nivel { get; set; }
        public Nullable<int> estado_b_b_nivel { get; set; }
        public Nullable<double> nivel_inv_comercializador { get; set; }
        public Nullable<double> nivel_critico_comercializador { get; set; }
        public Nullable<int> id_Producto { get; set; }
    
        public virtual producto producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tanque_bomba> tanque_bomba { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tanque_cubicacion> tanque_cubicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tanque_poliducto> tanque_poliducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tanque_Voe> Tanque_Voe { get; set; }
    }
}
