//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string mensaje { get; set; }
        public Nullable<int> id_User { get; set; }
        public Nullable<int> id_Categoria { get; set; }
        public Nullable<int> id_Terminal { get; set; }
        public Nullable<int> id_Subsistema { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Terminal Terminal { get; set; }
        public virtual User User { get; set; }
    }
}
