//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usr_profile
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updateAt { get; set; }
        public Nullable<System.DateTime> fecha_nacimeinto { get; set; }
        public string Cel { get; set; }
        public string Género { get; set; }
        public string Estado { get; set; }
        public byte[] Foto_usuario { get; set; }
        public int id_User { get; set; }
    
        public virtual User User { get; set; }
    }
}
